
// Code generated by tools/gen_shims. DO NOT EDIT.

package printer

import "github.com/withastro/compiler/internal"
import "github.com/withastro/compiler/internal/handler"
import "github.com/withastro/compiler/internal/printer"
import "github.com/withastro/compiler/internal/t"
import "github.com/withastro/compiler/internal/transform"
import _ "unsafe"

var ADD_ATTRIBUTE = printer.ADD_ATTRIBUTE
type ASTNode = printer.ASTNode
type ASTPoint = printer.ASTPoint
type ASTPosition = printer.ASTPosition
var BACKTICK = printer.BACKTICK
var CREATE_ASTRO = printer.CREATE_ASTRO
var CREATE_COMPONENT = printer.CREATE_COMPONENT
var CREATE_METADATA = printer.CREATE_METADATA
var CREATE_TRANSITION_SCOPE = printer.CREATE_TRANSITION_SCOPE
var DEFINE_SCRIPT_VARS = printer.DEFINE_SCRIPT_VARS
var DEFINE_STYLE_VARS = printer.DEFINE_STYLE_VARS
type ExtractedStatement = printer.ExtractedStatement
var FRAGMENT = printer.FRAGMENT
const JsonScriptText = printer.JsonScriptText
var MAYBE_RENDER_HEAD = printer.MAYBE_RENDER_HEAD
var MERGE_SLOTS = printer.MERGE_SLOTS
var METADATA = printer.METADATA
//go:linkname PrintCSS github.com/withastro/compiler/internal/printer.PrintCSS
func PrintCSS(sourcetext string, doc *astro.Node, opts transform.TransformOptions) printer.PrintCSSResult
type PrintCSSResult = printer.PrintCSSResult
type PrintResult = printer.PrintResult
//go:linkname PrintToJS github.com/withastro/compiler/internal/printer.PrintToJS
func PrintToJS(sourcetext string, n *astro.Node, cssLen int, opts transform.TransformOptions, h *handler.Handler) printer.PrintResult
//go:linkname PrintToJSON github.com/withastro/compiler/internal/printer.PrintToJSON
func PrintToJSON(sourcetext string, n *astro.Node, opts t.ParseOptions) printer.PrintResult
//go:linkname PrintToTSX github.com/withastro/compiler/internal/printer.PrintToTSX
func PrintToTSX(sourcetext string, n *astro.Node, opts printer.TSXOptions, transformOpts transform.TransformOptions, h *handler.Handler) printer.PrintResult
var RENDER_COMPONENT = printer.RENDER_COMPONENT
var RENDER_HEAD = printer.RENDER_HEAD
var RENDER_SCRIPT = printer.RENDER_SCRIPT
var RENDER_SLOT = printer.RENDER_SLOT
var RENDER_TRANSITION = printer.RENDER_TRANSITION
var RESULT = printer.RESULT
const RawText = printer.RawText
type RenderOptions = printer.RenderOptions
var SLOTS = printer.SLOTS
var SPREAD_ATTRIBUTES = printer.SPREAD_ATTRIBUTES
var ScriptJSONMimeTypes = printer.ScriptJSONMimeTypes
var ScriptMimeTypes = printer.ScriptMimeTypes
const ScriptText = printer.ScriptText
const StyleText = printer.StyleText
var TEMPLATE_TAG = printer.TEMPLATE_TAG
type TSXExtractedTag = printer.TSXExtractedTag
type TSXOptions = printer.TSXOptions
type TSXRanges = printer.TSXRanges
const Text = printer.Text
type TextType = printer.TextType
var UNESCAPE_HTML = printer.UNESCAPE_HTML
const UnknownScriptText = printer.UnknownScriptText
