
// Code generated by tools/gen_shims. DO NOT EDIT.

package handler

import "github.com/withastro/compiler/internal/handler"
import "github.com/withastro/compiler/internal/loc"
import _ "unsafe"

//go:linkname ErrorToMessage github.com/withastro/compiler/internal/handler.ErrorToMessage
func ErrorToMessage(h *handler.Handler, severity loc.DiagnosticSeverity, err error) loc.DiagnosticMessage
type Handler = handler.Handler
//go:linkname NewHandler github.com/withastro/compiler/internal/handler.NewHandler
func NewHandler(sourcetext string, filename string) *handler.Handler
