
// Code generated by tools/gen_shims. DO NOT EDIT.

package handler

import "github.com/withastro/compiler/internal/handler"
import "github.com/withastro/compiler/internal/loc"
import "github.com/withastro/compiler/internal/sourcemap"
import "unsafe"

//go:linkname ErrorToMessage github.com/withastro/compiler/internal/handler.ErrorToMessage
func ErrorToMessage(h *handler.Handler, severity loc.DiagnosticSeverity, err error) loc.DiagnosticMessage
type Handler = handler.Handler
type extra_Handler struct {
  sourcetext string
  filename string
  builder sourcemap.ChunkBuilder
  errors []error
  warnings []error
  infos []error
  hints []error
}
func Handler_errors(v *handler.Handler) []error {
  return ((*extra_Handler)(unsafe.Pointer(v))).errors
}
//go:linkname NewHandler github.com/withastro/compiler/internal/handler.NewHandler
func NewHandler(sourcetext string, filename string) *handler.Handler
