// Code generated by gen-rule-config.ts; DO NOT EDIT.

package linter

import (
	"encoding/json"

	"github.com/auvred/golar/internal/linter/rule"

	"github.com/auvred/golar/internal/linter/rules/explicit-anys"
)

func setupRule(ruleName string, ctx rule.Context, options []byte) rule.Listeners {
	// TODO: use ints instead of strings
	switch ruleName {
	case "explicit-anys":
		var opts explicit_anys.Options
		if err := json.Unmarshal(options, &opts); err != nil {
			panic(err)
		}
		return explicit_anys.Rule(ctx, opts)
	default:
		panic("unknown rule name: " + ruleName)
	}
}
