packages:
  - docs
  - e2e/all-languages/fixture
  - e2e/ember-emit/fixture
  - e2e/lint-typecheck/fixture
  - e2e/service-code-error/fixture
  - e2e/typecheck-gitignore/fixture
  - e2e/typecheck-implicit-files/fixture
  - e2e/vue-emit/fixture
  - e2e/vue-expect-error/fixture
  - e2e/vue-plugins/fixture
  - e2e/vue-tsc-incremental/fixture
  - e2e/vue-unknown-component/fixture
  - e2e/vue-vitepress/fixture
  - packages/*
  - generated-packages/*

patchedDependencies:
  vitest: patches/vitest.patch
