//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode/utf8"
)

var diagnosticMessages = []string{
	`Single file component can contain only one <script setup> element.`,
	`Single file component can contain only one <template> element.`,
	`Single file component can contain only one <script> element.`,
	`{0} has no adjacent v-if or v-else-if.`,
	`Elements cannot have multiple {0} with the same name.`,
	`Multiple conditional directives cannot coexist on the same element.`,
	`{0} is missing expression.`,
	`Duplicate {0} call.`,
	`Slot does not belong to the parent component.`,
  `Duplicate model name "{0}".`,
}

func main() {
	var b strings.Builder

	b.WriteString(`// Code generated by generate.go; DO NOT EDIT.

package vue_diagnostics

import "github.com/microsoft/typescript-go/shim/diagnostics"

//go:generate go run generate.go

`)

	var init strings.Builder

	for i, msg := range diagnosticMessages {
		b.WriteString("var ")
		identifierStart := b.Len()
		prevUnderscore := false
		for i := 0; i < len(msg); {
			r, size := utf8.DecodeRuneInString(msg[i:])
			if r == '{' && i + 2 < len(msg) && '0' <= msg[i+1] && msg[i+1] <= '9' && msg[i+2] == '}' {
				if prevUnderscore {
					b.WriteByte('_')
					prevUnderscore = false
				}
				b.WriteString("X_")
				b.WriteByte(msg[i+1])
				i += 3
				continue
			}
			if ('A' <= r && r <= 'Z') || ('a' <= r && r <= 'z') {
				if prevUnderscore {
					b.WriteByte('_')
					prevUnderscore = false
				}
				b.WriteRune(r)
			} else  {
				prevUnderscore = true
			}
			i += size
		}

		identifier := b.String()[identifierStart:b.Len()]

		b.WriteString(" = &diagnostics.Message{}\n")

		init.WriteString(fmt.Sprintf(`
	diagnostics.Message_Set_code(%[1]s, %[2]d)
	diagnostics.Message_Set_category(%[1]s, diagnostics.CategoryError)
	diagnostics.Message_Set_key(%[1]s, %[1]q)
	diagnostics.Message_Set_text(%[1]s, %[3]q)`, identifier, 1_000_000 + i, msg))
	}

	b.WriteString("func init() {\n")
	b.WriteString(init.String())
	b.WriteString("}\n")

	res, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(err)
	}

	if err := os.WriteFile("diagnostics.go", res, 0o666); err != nil {
		panic(err)
	}
}
