
// Code generated by tools/gen_shims. DO NOT EDIT.

package astro

import "github.com/withastro/compiler/internal"
import "github.com/withastro/compiler/internal/handler"
import "io"
import "strings"
import _ "unsafe"

type Attribute = astro.Attribute
type AttributeType = astro.AttributeType
const CommentNode = astro.CommentNode
const CommentToken = astro.CommentToken
const DoctypeNode = astro.DoctypeNode
const DoctypeToken = astro.DoctypeToken
const DocumentNode = astro.DocumentNode
const ElementNode = astro.ElementNode
const EmptyAttribute = astro.EmptyAttribute
const EndExpressionToken = astro.EndExpressionToken
const EndTagToken = astro.EndTagToken
var ErrBufferExceeded = astro.ErrBufferExceeded
const ErrorNode = astro.ErrorNode
const ErrorToken = astro.ErrorToken
//go:linkname EscapeString github.com/withastro/compiler/internal.EscapeString
func EscapeString(s string) string
type Expression = astro.Expression
const ExpressionAttribute = astro.ExpressionAttribute
const ExpressionNode = astro.ExpressionNode
const FrontmatterClosed = astro.FrontmatterClosed
const FrontmatterFenceToken = astro.FrontmatterFenceToken
const FrontmatterInitial = astro.FrontmatterInitial
const FrontmatterNode = astro.FrontmatterNode
const FrontmatterOpen = astro.FrontmatterOpen
type FrontmatterState = astro.FrontmatterState
//go:linkname GetAttribute github.com/withastro/compiler/internal.GetAttribute
func GetAttribute(n *astro.Node, key string) *astro.Attribute
//go:linkname HashString github.com/withastro/compiler/internal.HashString
func HashString(str string) string
type HydratedComponentMetadata = astro.HydratedComponentMetadata
const ImplicitNodeMarker = astro.ImplicitNodeMarker
//go:linkname IsKnownDirective github.com/withastro/compiler/internal.IsKnownDirective
func IsKnownDirective(element *astro.Node, attr *astro.Attribute) bool
//go:linkname NewTokenizer github.com/withastro/compiler/internal.NewTokenizer
func NewTokenizer(r io.Reader) *astro.Tokenizer
//go:linkname NewTokenizerFragment github.com/withastro/compiler/internal.NewTokenizerFragment
func NewTokenizerFragment(r io.Reader, contextTag string) *astro.Tokenizer
type Node = astro.Node
type NodeType = astro.NodeType
//go:linkname Parse github.com/withastro/compiler/internal.Parse
func Parse(r io.Reader) (*astro.Node, error)
//go:linkname ParseFragmentWithOptions github.com/withastro/compiler/internal.ParseFragmentWithOptions
func ParseFragmentWithOptions(r io.Reader, context *astro.Node, opts ...astro.ParseOption) ([]*astro.Node, error)
type ParseOption = astro.ParseOption
//go:linkname ParseOptionEnableLiteral github.com/withastro/compiler/internal.ParseOptionEnableLiteral
func ParseOptionEnableLiteral(enable bool) astro.ParseOption
//go:linkname ParseOptionEnableScripting github.com/withastro/compiler/internal.ParseOptionEnableScripting
func ParseOptionEnableScripting(enable bool) astro.ParseOption
//go:linkname ParseOptionWithHandler github.com/withastro/compiler/internal.ParseOptionWithHandler
func ParseOptionWithHandler(h *handler.Handler) astro.ParseOption
//go:linkname ParseWithOptions github.com/withastro/compiler/internal.ParseWithOptions
func ParseWithOptions(r io.Reader, opts ...astro.ParseOption) (*astro.Node, error)
//go:linkname PrintToSource github.com/withastro/compiler/internal.PrintToSource
func PrintToSource(buf *strings.Builder, node *astro.Node)
const QuotedAttribute = astro.QuotedAttribute
const RawNode = astro.RawNode
const RenderHeadNode = astro.RenderHeadNode
const SelfClosingTagToken = astro.SelfClosingTagToken
const ShorthandAttribute = astro.ShorthandAttribute
const SpreadAttribute = astro.SpreadAttribute
const StartExpressionToken = astro.StartExpressionToken
const StartTagToken = astro.StartTagToken
const TemplateLiteralAttribute = astro.TemplateLiteralAttribute
const TextNode = astro.TextNode
const TextToken = astro.TextToken
type Token = astro.Token
type TokenType = astro.TokenType
type Tokenizer = astro.Tokenizer
//go:linkname UnescapeString github.com/withastro/compiler/internal.UnescapeString
func UnescapeString(s string) string
