
// Code generated by tools/gen_shims. DO NOT EDIT.

package diagnosticwriter

import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/diagnosticwriter"
import "github.com/microsoft/typescript-go/internal/locale"
import "io"
import _ "unsafe"

type ASTDiagnostic = diagnosticwriter.ASTDiagnostic
//go:linkname CompareASTDiagnostics github.com/microsoft/typescript-go/internal/diagnosticwriter.CompareASTDiagnostics
func CompareASTDiagnostics(a *diagnosticwriter.ASTDiagnostic, b *diagnosticwriter.ASTDiagnostic) int
type Diagnostic = diagnosticwriter.Diagnostic
type ErrorSummary = diagnosticwriter.ErrorSummary
type FileLike = diagnosticwriter.FileLike
//go:linkname FlattenDiagnosticMessage github.com/microsoft/typescript-go/internal/diagnosticwriter.FlattenDiagnosticMessage
func FlattenDiagnosticMessage(d diagnosticwriter.Diagnostic, newLine string, locale locale.Locale) string
//go:linkname FormatDiagnosticWithColorAndContext github.com/microsoft/typescript-go/internal/diagnosticwriter.FormatDiagnosticWithColorAndContext
func FormatDiagnosticWithColorAndContext(output io.Writer, diagnostic diagnosticwriter.Diagnostic, formatOpts *diagnosticwriter.FormattingOptions)
//go:linkname FormatDiagnosticsStatusAndTime github.com/microsoft/typescript-go/internal/diagnosticwriter.FormatDiagnosticsStatusAndTime
func FormatDiagnosticsStatusAndTime(output io.Writer, time string, diag diagnosticwriter.Diagnostic, formatOpts *diagnosticwriter.FormattingOptions)
//go:linkname FormatDiagnosticsStatusWithColorAndTime github.com/microsoft/typescript-go/internal/diagnosticwriter.FormatDiagnosticsStatusWithColorAndTime
func FormatDiagnosticsStatusWithColorAndTime(output io.Writer, time string, diag diagnosticwriter.Diagnostic, formatOpts *diagnosticwriter.FormattingOptions)
//go:linkname FormatDiagnosticsWithColorAndContext github.com/microsoft/typescript-go/internal/diagnosticwriter.FormatDiagnosticsWithColorAndContext
func FormatDiagnosticsWithColorAndContext(output io.Writer, diags []diagnosticwriter.Diagnostic, formatOpts *diagnosticwriter.FormattingOptions)
type FormattedWriter = diagnosticwriter.FormattedWriter
type FormattingOptions = diagnosticwriter.FormattingOptions
//go:linkname FromASTDiagnostics github.com/microsoft/typescript-go/internal/diagnosticwriter.FromASTDiagnostics
func FromASTDiagnostics(diags []*ast.Diagnostic) []diagnosticwriter.Diagnostic
var ScreenStartingCodes = diagnosticwriter.ScreenStartingCodes
//go:linkname TryClearScreen github.com/microsoft/typescript-go/internal/diagnosticwriter.TryClearScreen
func TryClearScreen(output io.Writer, diag diagnosticwriter.Diagnostic, options *core.CompilerOptions) bool
//go:linkname WrapASTDiagnostic github.com/microsoft/typescript-go/internal/diagnosticwriter.WrapASTDiagnostic
func WrapASTDiagnostic(d *ast.Diagnostic) *diagnosticwriter.ASTDiagnostic
//go:linkname WrapASTDiagnostics github.com/microsoft/typescript-go/internal/diagnosticwriter.WrapASTDiagnostics
func WrapASTDiagnostics(diags []*ast.Diagnostic) []*diagnosticwriter.ASTDiagnostic
//go:linkname WriteErrorSummaryText github.com/microsoft/typescript-go/internal/diagnosticwriter.WriteErrorSummaryText
func WriteErrorSummaryText(output io.Writer, allDiagnostics []diagnosticwriter.Diagnostic, formatOpts *diagnosticwriter.FormattingOptions)
//go:linkname WriteFlattenedASTDiagnosticMessage github.com/microsoft/typescript-go/internal/diagnosticwriter.WriteFlattenedASTDiagnosticMessage
func WriteFlattenedASTDiagnosticMessage(writer io.Writer, diagnostic *ast.Diagnostic, newline string, locale locale.Locale)
//go:linkname WriteFlattenedDiagnosticMessage github.com/microsoft/typescript-go/internal/diagnosticwriter.WriteFlattenedDiagnosticMessage
func WriteFlattenedDiagnosticMessage(writer io.Writer, diagnostic diagnosticwriter.Diagnostic, newline string, locale locale.Locale)
//go:linkname WriteFormatDiagnostic github.com/microsoft/typescript-go/internal/diagnosticwriter.WriteFormatDiagnostic
func WriteFormatDiagnostic(output io.Writer, diagnostic diagnosticwriter.Diagnostic, formatOpts *diagnosticwriter.FormattingOptions)
//go:linkname WriteFormatDiagnostics github.com/microsoft/typescript-go/internal/diagnosticwriter.WriteFormatDiagnostics
func WriteFormatDiagnostics(output io.Writer, diagnostics []diagnosticwriter.Diagnostic, formatOpts *diagnosticwriter.FormattingOptions)
//go:linkname WriteLocation github.com/microsoft/typescript-go/internal/diagnosticwriter.WriteLocation
func WriteLocation(output io.Writer, file diagnosticwriter.FileLike, pos int, formatOpts *diagnosticwriter.FormattingOptions, writeWithStyleAndReset diagnosticwriter.FormattedWriter)
