
// Code generated by tools/gen_shims. DO NOT EDIT.

package loc

import "github.com/withastro/compiler/internal/loc"

type DiagnosticCode = loc.DiagnosticCode
type DiagnosticLocation = loc.DiagnosticLocation
type DiagnosticMessage = loc.DiagnosticMessage
type DiagnosticSeverity = loc.DiagnosticSeverity
const ERROR = loc.ERROR
const ERROR_FRAGMENT_SHORTHAND_ATTRS = loc.ERROR_FRAGMENT_SHORTHAND_ATTRS
const ERROR_UNMATCHED_IMPORT = loc.ERROR_UNMATCHED_IMPORT
const ERROR_UNSUPPORTED_SLOT_ATTRIBUTE = loc.ERROR_UNSUPPORTED_SLOT_ATTRIBUTE
const ERROR_UNTERMINATED_JS_COMMENT = loc.ERROR_UNTERMINATED_JS_COMMENT
const ERROR_UNTERMINATED_STRING = loc.ERROR_UNTERMINATED_STRING
const ErrorType = loc.ErrorType
type ErrorWithRange = loc.ErrorWithRange
const HINT = loc.HINT
const HintType = loc.HintType
const INFO = loc.INFO
const InformationType = loc.InformationType
type Loc = loc.Loc
type Range = loc.Range
type Span = loc.Span
type TSXRange = loc.TSXRange
const WARNING = loc.WARNING
const WARNING_CANNOT_DEFINE_VARS = loc.WARNING_CANNOT_DEFINE_VARS
const WARNING_CANNOT_RERUN = loc.WARNING_CANNOT_RERUN
const WARNING_DEPRECATED_DIRECTIVE = loc.WARNING_DEPRECATED_DIRECTIVE
const WARNING_IGNORED_DIRECTIVE = loc.WARNING_IGNORED_DIRECTIVE
const WARNING_INVALID_SPREAD = loc.WARNING_INVALID_SPREAD
const WARNING_SET_WITH_CHILDREN = loc.WARNING_SET_WITH_CHILDREN
const WARNING_UNCLOSED_HTML_TAG = loc.WARNING_UNCLOSED_HTML_TAG
const WARNING_UNEXPECTED_CHARACTER = loc.WARNING_UNEXPECTED_CHARACTER
const WARNING_UNSUPPORTED_EXPRESSION = loc.WARNING_UNSUPPORTED_EXPRESSION
const WARNING_UNTERMINATED_HTML_COMMENT = loc.WARNING_UNTERMINATED_HTML_COMMENT
const WarningType = loc.WarningType
