// Code generated by gen-rule-config.ts; DO NOT EDIT.

import { rule as explicitAnys } from '../../../internal/linter/rules/explicit-anys/config.ts'

export const rules = {
	'explicit-anys': explicitAnys,
} as const
