
// Code generated by tools/gen_shims. DO NOT EDIT.

package fourslash

import "github.com/microsoft/typescript-go/internal/fourslash"
import "github.com/microsoft/typescript-go/internal/lsp/lsproto"
import "testing"
import _ "unsafe"

var AnyTextEdits = fourslash.AnyTextEdits
type ApplyCodeActionFromCompletionOptions = fourslash.ApplyCodeActionFromCompletionOptions
type CompletionsExpectedCodeAction = fourslash.CompletionsExpectedCodeAction
type CompletionsExpectedItem = fourslash.CompletionsExpectedItem
type CompletionsExpectedItemDefaults = fourslash.CompletionsExpectedItemDefaults
type CompletionsExpectedItems = fourslash.CompletionsExpectedItems
type CompletionsExpectedList = fourslash.CompletionsExpectedList
type EditRange = fourslash.EditRange
type ExpectedCompletionEditRange = fourslash.ExpectedCompletionEditRange
type FourslashTest = fourslash.FourslashTest
//go:linkname GetDefaultCapabilities github.com/microsoft/typescript-go/internal/fourslash.GetDefaultCapabilities
func GetDefaultCapabilities() *lsproto.ClientCapabilities
type Ignored = fourslash.Ignored
type Marker = fourslash.Marker
type MarkerInput = fourslash.MarkerInput
type MarkerOrRange = fourslash.MarkerOrRange
type MarkerOrRangeOrName = fourslash.MarkerOrRangeOrName
//go:linkname NewFourslash github.com/microsoft/typescript-go/internal/fourslash.NewFourslash
func NewFourslash(t *testing.T, capabilities *lsproto.ClientCapabilities, content string) (*fourslash.FourslashTest, func())
//go:linkname ParseTestData github.com/microsoft/typescript-go/internal/fourslash.ParseTestData
func ParseTestData(t *testing.T, contents string, fileName string) fourslash.TestData
type RangeMarker = fourslash.RangeMarker
type SignatureHelpCase = fourslash.SignatureHelpCase
//go:linkname SkipIfFailing github.com/microsoft/typescript-go/internal/fourslash.SkipIfFailing
func SkipIfFailing(t *testing.T)
type TestData = fourslash.TestData
type TestFileInfo = fourslash.TestFileInfo
type VerifyCompletionsResult = fourslash.VerifyCompletionsResult
type VerifySignatureHelpOptions = fourslash.VerifySignatureHelpOptions
type VerifyWorkspaceSymbolCase = fourslash.VerifyWorkspaceSymbolCase
