
// Code generated by tools/gen_shims. DO NOT EDIT.

package transform

import "github.com/withastro/compiler/internal"
import "github.com/withastro/compiler/internal/handler"
import "github.com/withastro/compiler/internal/transform"
import _ "unsafe"

//go:linkname AddComponentProps github.com/withastro/compiler/internal/transform.AddComponentProps
func AddComponentProps(doc *astro.Node, n *astro.Node, opts *transform.TransformOptions)
//go:linkname AddDefineVars github.com/withastro/compiler/internal/transform.AddDefineVars
func AddDefineVars(n *astro.Node, values []string) bool
//go:linkname AnnotateElement github.com/withastro/compiler/internal/transform.AnnotateElement
func AnnotateElement(n *astro.Node, opts transform.TransformOptions)
//go:linkname AttrIndex github.com/withastro/compiler/internal/transform.AttrIndex
func AttrIndex(n *astro.Node, key string) int
const DATA_ASTRO_RELOAD = transform.DATA_ASTRO_RELOAD
//go:linkname ExtractScript github.com/withastro/compiler/internal/transform.ExtractScript
func ExtractScript(doc *astro.Node, n *astro.Node, opts *transform.TransformOptions, h *handler.Handler)
//go:linkname ExtractStyles github.com/withastro/compiler/internal/transform.ExtractStyles
func ExtractStyles(doc *astro.Node, opts *transform.TransformOptions)
//go:linkname GetAttr github.com/withastro/compiler/internal/transform.GetAttr
func GetAttr(n *astro.Node, key string) *astro.Attribute
//go:linkname GetDefineVars github.com/withastro/compiler/internal/transform.GetDefineVars
func GetDefineVars(styles []*astro.Node) []string
//go:linkname GetQuotedAttr github.com/withastro/compiler/internal/transform.GetQuotedAttr
func GetQuotedAttr(n *astro.Node, key string) string
//go:linkname HasAttr github.com/withastro/compiler/internal/transform.HasAttr
func HasAttr(n *astro.Node, key string) bool
//go:linkname HasInlineDirective github.com/withastro/compiler/internal/transform.HasInlineDirective
func HasInlineDirective(n *astro.Node) bool
//go:linkname HasSetDirective github.com/withastro/compiler/internal/transform.HasSetDirective
func HasSetDirective(n *astro.Node) bool
//go:linkname HintAboutImplicitInlineDirective github.com/withastro/compiler/internal/transform.HintAboutImplicitInlineDirective
func HintAboutImplicitInlineDirective(n *astro.Node, h *handler.Handler)
type ImportMatch = transform.ImportMatch
//go:linkname IsHoistable github.com/withastro/compiler/internal/transform.IsHoistable
func IsHoistable(n *astro.Node, renderScriptEnabled bool) bool
//go:linkname IsImplicitNode github.com/withastro/compiler/internal/transform.IsImplicitNode
func IsImplicitNode(n *astro.Node) bool
//go:linkname IsImplicitNodeMarker github.com/withastro/compiler/internal/transform.IsImplicitNodeMarker
func IsImplicitNodeMarker(attr astro.Attribute) bool
//go:linkname IsTopLevel github.com/withastro/compiler/internal/transform.IsTopLevel
func IsTopLevel(n *astro.Node) bool
var NeverScopedElements = transform.NeverScopedElements
var NeverScopedSelectors = transform.NeverScopedSelectors
//go:linkname NormalizeSetDirectives github.com/withastro/compiler/internal/transform.NormalizeSetDirectives
func NormalizeSetDirectives(doc *astro.Node, h *handler.Handler)
//go:linkname ResolveIdForMatch github.com/withastro/compiler/internal/transform.ResolveIdForMatch
func ResolveIdForMatch(id string, opts *transform.TransformOptions) string
const SERVER_DEFER = transform.SERVER_DEFER
//go:linkname ScopeElement github.com/withastro/compiler/internal/transform.ScopeElement
func ScopeElement(n *astro.Node, opts transform.TransformOptions)
//go:linkname ScopeStyle github.com/withastro/compiler/internal/transform.ScopeStyle
func ScopeStyle(styles []*astro.Node, opts transform.TransformOptions) bool
const TRANSITION_ANIMATE = transform.TRANSITION_ANIMATE
const TRANSITION_NAME = transform.TRANSITION_NAME
const TRANSITION_PERSIST = transform.TRANSITION_PERSIST
const TRANSITION_PERSIST_PROPS = transform.TRANSITION_PERSIST_PROPS
//go:linkname Transform github.com/withastro/compiler/internal/transform.Transform
func Transform(doc *astro.Node, opts transform.TransformOptions, h *handler.Handler) *astro.Node
type TransformOptions = transform.TransformOptions
//go:linkname TrimTrailingSpace github.com/withastro/compiler/internal/transform.TrimTrailingSpace
func TrimTrailingSpace(doc *astro.Node)
//go:linkname WarnAboutMisplacedReload github.com/withastro/compiler/internal/transform.WarnAboutMisplacedReload
func WarnAboutMisplacedReload(n *astro.Node, h *handler.Handler)
//go:linkname WarnAboutRerunOnExternalESMs github.com/withastro/compiler/internal/transform.WarnAboutRerunOnExternalESMs
func WarnAboutRerunOnExternalESMs(n *astro.Node, h *handler.Handler)
