import path from 'node:path'
import fs from 'node:fs/promises'
import { z } from 'zod'
import { typeOrValueSpecifier } from '../internal/linter/rule-creator.ts'
import spawn from 'nano-spawn'

const linterDir = path.join(import.meta.dirname, '..', 'internal', 'linter')
const golarPackageDir = path.join(
	import.meta.dirname,
	'..',
	'packages',
	'golar',
)
const ruleDirs = (
	await fs.readdir(path.join(linterDir, 'rules'), { withFileTypes: true })
).filter((r) => r.isDirectory())

const rules: {
	name: string
	jsName: string
	packageName: string
	hasOptions: boolean
}[] = []

for (const ruleDir of ruleDirs) {
	const rulePath = path.join(ruleDir.parentPath, ruleDir.name)
	const packageName = ruleDir.name.replaceAll('-', '_')

	let generatedFields = ''
	let hasTypeOrValueSpecifierOption = false

	const { rule } = await import(path.join(rulePath, 'config.ts'))

	const hasOptions = rule.options != null
	rules.push({
		name: ruleDir.name,
		jsName: ruleDir.name.replaceAll(/-(\w)/g, (_, letter) =>
			letter.toUpperCase(),
		),
		packageName,
		hasOptions,
	})

	if (!hasOptions) {
		continue
	}

	for (const [option, { def: _def }] of Object.entries(
		rule.options as Record<string, z.ZodType>,
	)) {
		const fieldName = option[0]!.toUpperCase() + option.slice(1)

		function invalid(msg: string): never {
			throw new Error(`${option}: ${msg}`)
		}
		if (_def.type !== 'default') {
			invalid('must specify .default()')
		}

		generatedFields += `${fieldName} `

		const def = _def as z.core.$ZodDefaultDef<any>
		if (def.innerType === typeOrValueSpecifier) {
			hasTypeOrValueSpecifierOption = true
			generatedFields += '[]rule.TypeOrValueSpecifier'
		} else {
			const innerDef = def.innerType.def as z.core.$ZodTypeDef
			switch (innerDef.type) {
				case 'string':
					generatedFields += 'string'
					break
				case 'boolean':
					generatedFields += 'bool'
					break
				case 'array': {
					const arrayDef = innerDef as z.core.$ZodTypeDef & {
						element: z.ZodType
					}
					if (arrayDef.element.def.type !== 'string') {
						invalid(`unknown array element type: ${arrayDef.element.def.type}`)
					}
					generatedFields += '[]string'
					break
				}
				default:
					invalid(`unknown inner type: ${innerDef.type}`)
			}
		}
		generatedFields += ` \`json:"${option}"\`\n`
	}

	let generated = `// Code generated by gen-rule-config.ts; DO NOT EDIT.

package ${packageName}

`

	if (hasTypeOrValueSpecifierOption) {
		generated += `import "github.com/auvred/golar/internal/linter/rule"

`
	}

	generated += `type Options struct {
${generatedFields}}
`

	const configGeneratedPath = path.join(rulePath, 'config_generated.go')
	await fs.writeFile(configGeneratedPath, generated)
	await gofmt(configGeneratedPath)
}

rules.sort((a, b) => a.name.localeCompare(b.name))

let rulesGenerated = `// Code generated by gen-rule-config.ts; DO NOT EDIT.

package linter

import (
	"encoding/json"

	"github.com/auvred/golar/internal/linter/rule"

${rules.map(({ name }) => `"github.com/auvred/golar/internal/linter/rules/${name}"`).join('\n')}
)

func setupRule(ruleName string, ctx rule.Context, options []byte) rule.Listeners {
	// TODO: use ints instead of strings
	switch ruleName {
${rules
	.map(
		({ name, packageName, hasOptions }) =>
			`case "${name}": ${
				hasOptions
					? `
		var opts ${packageName}.Options
		if err := json.Unmarshal(options, &opts); err != nil {
			panic(err)
		}
		return ${packageName}.Rule(ctx, opts)
	`
					: `
		return ${packageName}.Rule(ctx)
	`
			}`,
	)
	.join('')}default:
		panic("unknown rule name: " + ruleName)
	}
}
`

const rulesGeneratedPath = path.join(linterDir, 'rules_generated.go')
await fs.writeFile(rulesGeneratedPath, rulesGenerated)
await gofmt(rulesGeneratedPath)

let exportRulesGenerated = `// Code generated by gen-rule-config.ts; DO NOT EDIT.

${rules.map(({ name, jsName }) => `import { rule as ${jsName} } from '../../../internal/linter/rules/${name}/config.ts'`).join('\n')}

export const rules = {
${rules.map(({ name, jsName }) => `'${name}': ${jsName},`).join('\n')}
} as const
`

const exportRulesPath = path.join(
	golarPackageDir,
	'src',
	'builtin-rules.generated.ts',
)
await fs.writeFile(exportRulesPath, exportRulesGenerated)

await spawn('pnpm', ['prettier', '-w', exportRulesPath], { stdio: 'inherit' })

async function gofmt(filepath: string) {
	await spawn('gofmt', ['-w', filepath], { stdio: 'inherit' })
}
