/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package main */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "exports.go"

#include <stdint.h>
#include <stdlib.h>

void napi_call_threadsafe_function_any(uintptr_t func, uintptr_t data, size_t is_blocking);

typedef struct {
	uintptr_t program;
	uintptr_t source_file;
} golar_file_with_program;

#line 1 "cgo-generated-wrapper"

#line 3 "js_plugin.go"

#include <stdint.h>
#include <stdlib.h>

void napi_call_threadsafe_function_any(uintptr_t func, uintptr_t data, size_t is_blocking);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void golar_js_setSyncBuffer(uint32_t threadId, uintptr_t bufPtr, size_t bufLen);

/* Return type for golar_js_linter_RuleTesterLint */
struct golar_js_linter_RuleTesterLint_return {
	char* r0;
	size_t r1;
};
extern struct golar_js_linter_RuleTesterLint_return golar_js_linter_RuleTesterLint(char* files_data, size_t files_len, char* fileName_data, size_t fileName_len, char* ruleName_data, size_t ruleName_len, char* options_data, size_t options_len);
extern void golar_js_workspace_New(uintptr_t cbPtr);
extern void golar_js_workspace_ReadRequestedFileAt(uint32_t threadId);
extern void golar_js_workspace_ReadFileById(uint32_t threadId);
extern void golar_js_workspace_GetTypeAtLocation(uint32_t threadId);
extern void golar_js_workspace_Lint(void);
extern void golar_js_workspace_Report(uint32_t threadId);
extern void golar_js_tsc(uint32_t threadId, uintptr_t doneCbTsfn);
extern uint32_t golar_js_workspace_TypeCheck(void);
extern golar_file_with_program golar_workspace_get_requested_file(uintptr_t workspacePtr, uint32_t fileIdx);
extern uintptr_t golar_program_get_type_at_location(uintptr_t programPtr, uintptr_t nodePtr);
extern void golar_workspace_report(uintptr_t workspacePtr, uint32_t fileIdx, int32_t start, int32_t end, char* ruleNameData, size_t ruleNameLen, char* messageData, size_t messageLen);
extern void golar_js_registerJsCodegen(uint32_t threadId, uintptr_t createServiceCodeTsfn);
extern void golar_js_jsCodegenCreateServiceCodeResponse(uint32_t threadId);
extern void golar_js_registerIpcCodegen(void);

#ifdef __cplusplus
}
#endif
