#pragma once

#define napi_get_cb_info golar_napi_get_cb_info_ptr
#define napi_get_value_uint32 golar_napi_get_value_uint32_ptr
#define napi_get_arraybuffer_info golar_napi_get_arraybuffer_info_ptr
#define napi_get_value_string_utf8 golar_napi_get_value_string_utf8_ptr
#define napi_create_string_utf8 golar_napi_create_string_utf8_ptr
#define napi_get_undefined golar_napi_get_undefined_ptr
#define napi_call_function golar_napi_call_function_ptr
#define napi_create_threadsafe_function golar_napi_create_threadsafe_function_ptr
#define napi_get_named_property golar_napi_get_named_property_ptr
#define napi_create_function golar_napi_create_function_ptr
#define napi_create_uint32 golar_napi_create_uint32_ptr
#define napi_define_properties golar_napi_define_properties_ptr
#define napi_call_threadsafe_function golar_napi_call_threadsafe_function_ptr
